//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s,sw,sw,nw,nw,nw,sw,s,ne,n,n,n,s,ne,ne,sw,ne,n,ne,nw,ne,sw,ne,nw,ne,ne,ne,nw,sw,se,ne,se,ne,ne,se,se,s,sw,se,se,se,ne,se,nw,ne,s,s,s,s,s,se,sw,sw,ne,s,sw,nw,s,s,s,s,s,s,s,sw,s,sw,s,sw,s,se,se,sw,s,s,sw,sw,s,s,s,s,sw,sw,sw,sw,s,s,sw,nw,sw,sw,sw,sw,n,se,sw,sw,sw,sw,sw,ne,sw,sw,ne,sw,sw,sw,sw,sw,sw,nw,sw,nw,nw,nw,sw,sw,sw,nw,s,sw,nw,nw,sw,nw,nw,nw,se,ne,sw,nw,nw,nw,s,ne,nw,nw,s,nw,nw,s,nw,nw,n,nw,nw,nw,nw,nw,nw,nw,n,nw,nw,n,nw,nw,sw,nw,se,nw,nw,nw,n,nw,nw,n,nw,nw,nw,n,s,nw,nw,nw,nw,n,nw,nw,n,ne,n,n,nw,n,n,n,nw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D11 {
            get {
                return ResourceManager.GetString("input_D11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 &lt;-&gt; 82
        ///1 &lt;-&gt; 41, 1402
        ///2 &lt;-&gt; 454, 1690
        ///3 &lt;-&gt; 533, 1726
        ///4 &lt;-&gt; 82
        ///5 &lt;-&gt; 202, 1769
        ///6 &lt;-&gt; 682, 789, 1295
        ///7 &lt;-&gt; 1243, 1500
        ///8 &lt;-&gt; 1630
        ///9 &lt;-&gt; 847, 1922
        ///10 &lt;-&gt; 446
        ///11 &lt;-&gt; 98, 172, 859, 1303
        ///12 &lt;-&gt; 1748
        ///13 &lt;-&gt; 334
        ///14 &lt;-&gt; 850, 1537, 1627, 1747
        ///15 &lt;-&gt; 194, 722, 1091, 1290
        ///16 &lt;-&gt; 537, 965, 1642
        ///17 &lt;-&gt; 371
        ///18 &lt;-&gt; 422, 436, 1795
        ///19 &lt;-&gt; 487, 872, 1845
        ///20 &lt;-&gt; 423, 561, 1313, 1984
        ///21 &lt;-&gt; 62, 760
        ///22 &lt;-&gt; 62, 126, 586, 1472
        ///23 &lt;-&gt; 1057, 1809, 1938
        ///24 &lt;-&gt; 24, 986
        ///25 &lt;-&gt; 1758
        ///26 &lt;-&gt; 1780
        ///27 &lt;-&gt; 622, 7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D12 {
            get {
                return ResourceManager.GetString("input_D12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 3
        ///1: 3
        ///2: 3
        ///3: 3
        ///4: 3
        ///.
        /// </summary>
        internal static string input_D13 {
            get {
                return ResourceManager.GetString("input_D13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nyot babgr babgr kqtu kqtu kzshonp ylyk psqk
        ///iix ewj rojvbkk phrij iix zuajnk tadv givslju ewj bda
        ///isjur jppvano vctnpjp ngwzdq pxqfrk mnxxes zqwgnd giqh
        ///ojufqke gpd olzirc jfao cjfh rcivvw pqqpudp
        ///ilgomox extiffg ylbd nqxhk lsi isl nrho yom
        ///feauv scstmie qgbod enpltx jrhlxet qps lejrtxh
        ///wlrxtdo tlwdxor ezg ztp uze xtmw neuga aojrixu zpt
        ///wchrl pzibt nvcae wceb
        ///rdwytj kxuyet bqnzlv nyntjan dyrpsn zhi kbxlj ivo
        ///dab mwiz bapjpz jbzppa
        ///hbcudl tsfvtc zlqgpuk xoxbuh whmo atsxt pzkivuo wsa gjoevr hbcudl        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D4 {
            get {
                return ResourceManager.GetString("input_D4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///1
        ///0
        ///-1
        ///-3
        ///0
        ///-5
        ///-1
        ///2
        ///0
        ///-1
        ///-3
        ///-9
        ///-5
        ///-1
        ///-9
        ///2
        ///2
        ///-13
        ///-7
        ///-13
        ///-18
        ///0
        ///0
        ///-21
        ///-10
        ///-2
        ///-12
        ///-18
        ///-4
        ///-27
        ///-24
        ///-16
        ///-10
        ///-24
        ///-12
        ///-5
        ///-31
        ///-17
        ///-10
        ///-22
        ///-16
        ///-3
        ///-10
        ///-5
        ///-37
        ///-16
        ///-4
        ///-8
        ///-1
        ///-44
        ///-12
        ///-38
        ///-42
        ///-27
        ///-9
        ///-52
        ///-13
        ///-12
        ///-36
        ///-26
        ///2
        ///-48
        ///-2
        ///-3
        ///-17
        ///1
        ///-51
        ///-47
        ///-68
        ///-42
        ///0
        ///-53
        ///-47
        ///-34
        ///-17
        ///-15
        ///-10
        ///-76
        ///-53
        ///-58
        ///-24
        ///-62
        ///-78
        ///-11
        ///-5
        ///-71
        ///-52
        ///-41
        ///-84
        ///-57
        ///-63
        ///-88
        ///-11
        ///-61
        ///-55
        ///-85
        ///-61
        ///-87
        ///-57
        ///-46
        ///-94
        ///-19
        ///-31
        ///-84
        ///-60
        ///-7
        ///-31
        ///-25
        ///-90
        ///-108
        ///-79
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D5 {
            get {
                return ResourceManager.GetString("input_D5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mypyemv (1058) -&gt; tdssotr, pebnvks, zaulju
        ///snslv (48)
        ///aytbgf (30)
        ///mkcrsy (42)
        ///shwcd (42)
        ///muwcoy (63)
        ///dabfreg (49)
        ///iblvv (68)
        ///qqircn (401)
        ///pwpnfx (67)
        ///tlnztuz (60)
        ///ctglahh (17)
        ///pjkgn (170) -&gt; pstttg, xdkoxrg, cvuvxi
        ///ulasjv (114) -&gt; tkeney, zaffbku
        ///ojoim (139) -&gt; obebr, zxwlsj
        ///vhxxnj (109) -&gt; ooaouu, vraxbmd
        ///blbjzdr (40)
        ///iuctosc (12) -&gt; bqmayvq, yjzvbcb, takuy, qlsfhyp
        ///mfafdfn (73)
        ///egfrye (72) -&gt; uwxizpk, igbamrm
        ///cqokt (1487) -&gt; sjmfsib, ubspq, wsaugv
        ///ekorcyg (67)
        ///sfyxd (83)
        ///trkiub (65) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D7 {
            get {
                return ResourceManager.GetString("input_D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to koq inc 675 if xrh &gt;= -6
        ///it inc -402 if s &lt; -1
        ///g inc 283 if oj != -3
        ///it inc 355 if y &lt;= 5
        ///do dec 553 if g != 288
        ///ix dec 162 if hwz != 4
        ///gsz dec -738 if koq &lt;= 682
        ///s dec 941 if mh == 8
        ///ix dec -783 if yor &lt; 10
        ///rzc inc -583 if bp &lt; 9
        ///ix dec -186 if koq &lt;= 680
        ///ix dec 0 if ehw &gt; 2
        ///mh inc -830 if xrh &gt;= -9
        ///sql inc 242 if oj &lt;= 1
        ///bp dec 243 if a &lt; 5
        ///hwz dec -856 if ykc != 0
        ///zx inc 832 if rzc &gt; -588
        ///oj dec -213 if sql != 242
        ///gsz dec -910 if xrh != 3
        ///mh dec -129 if a &lt;= 5
        ///yor inc -772 if a == 0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D8 {
            get {
                return ResourceManager.GetString("input_D8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{}},{{&lt;!!!&gt;&gt;,{&lt;!&gt;},&lt;!&gt;},&lt;&lt;a&gt;}},{{},{}},{{{&lt;}&gt;}},{{{&lt;e},!!!&gt;,io!!!&gt;!&gt;},&lt;!&gt;},&lt;!!!&gt;},&lt;&quot;!!&gt;},{}}},{&lt;ee!!!&gt;&lt;&gt;,{&lt;,}}&lt;&lt;!!,&lt;{,!!}ie!&gt;&gt;}}}},{{&lt;a!&gt;},&lt;!!!!!&gt;},&lt;!!!!!&gt;!!!ae&apos;&apos;!e&gt;,&lt;eu&quot;{!!!&gt;!!}!,!!!&gt;!&gt;},&lt;a!&gt;},&lt;i&quot;!!!o&gt;},{{&lt;!!!&gt;!o!&gt;,&lt;e!!{&apos;{&quot;,&quot;!!u}a!!!!!&gt;},&lt;!&gt;},&lt;&apos;&gt;,&lt;!&gt;,&lt;{&lt;oai,&apos;e&gt;},{{},{&lt;&apos;!&gt;,&lt;&quot;!&gt;},&lt;!!ai&lt;!!!!!&gt;},&lt;,{e!&gt;,&lt;&gt;}},{{{},{&lt;e&apos;a&lt;!!u!!!&gt;!u&gt;}},{&lt;a&quot;ie!!{e&quot;!&gt;,,!&gt;&gt;},{{&lt;!!!!}!&gt;},&lt;!&gt;,&lt;}&apos;{!!o&quot;&apos;u!&apos;!!&gt;,{&lt;au!&gt;!&gt;,&lt;&quot;&apos;oa,!&gt;&gt;}},{{{&lt;!!{!&gt;},&lt;{u!e{i!&gt;,&lt;{!!&apos;a}!&gt;,&lt;&lt;!&gt;},&lt;&gt;}},&lt;!!!!&lt;!!!&gt;}}u{!!!&gt;&gt;},{&lt;!&gt;},&lt;}!&gt;},&lt;!&gt;&quot;!!,u&gt;}}}},{{{&lt;{&lt;&quot;!&gt;},&lt;!&gt;}, [rest of string was truncate....
        /// </summary>
        internal static string input_D9 {
            get {
                return ResourceManager.GetString("input_D9", resourceCulture);
            }
        }
    }
}
