//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC2016.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC2016.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2, L3, R2, R4, L2, L1, R2, R4, R1, L4, L5, R5, R5, R2, R2, R1, L2, L3, L2, L1, R3, L5, R187, R1, R4, L1, R5, L3, L4, R50, L4, R2, R70, L3, L2, R4, R3, R194, L3, L4, L4, L3, L4, R4, R5, L1, L5, L4, R1, L2, R4, L5, L3, R4, L5, L5, R5, R3, R5, L2, L4, R4, L1, R3, R1, L1, L2, R2, R2, L3, R3, R2, R5, R2, R5, L3, R2, L5, R1, R2, R2, L4, L5, L1, L4, R4, R3, R1, R2, L1, L2, R4, R5, L2, R3, L4, L5, L5, L4, R4, L2, R1, R1, L2, L3, L2, R2, L4, R3, R2, L1, L3, L2, L4, L4, R2, L3, L3, R2, L4, L3, R4, R3, L2, L1, L4, R4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D01 {
            get {
                return ResourceManager.GetString("input_D01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LURLLLLLDUULRDDDRLRDDDUDDUULLRLULRURLRRDULUUURDUURLRDRRURUURUDDRDLRRLDDDDLLDURLDUUUDRDDDLULLDDLRLRRRLDLDDDDDLUUUDLUULRDUDLDRRRUDUDDRULURULDRUDLDUUUDLUDURUURRUUDRLDURRULURRURUUDDLRLDDDDRDRLDDLURLRDDLUDRLLRURRURRRURURRLLRLDRDLULLUDLUDRURDLRDUUDDUUDRLUDDLRLUDLLURDRUDDLRURDULLLUDDURULDRLUDLUDLULRRUUDDLDRLLUULDDURLURRRRUUDRUDLLDRUDLRRDUDUUURRULLDLDDRLUURLDUDDRLDRLDULDDURDLUUDRRLDRLLLRRRDLLLLURDLLLUDRUULUULLRLRDLULRLURLURRRDRLLDLDRLLRLULRDDDLUDDLLLRRLLLUURLDRULLDURDLULUDLRLDLUDURLLLURUUUDRRRULRDURLLURRLDLRLDLDRRU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D02 {
            get {
                return ResourceManager.GetString("input_D02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   883  357  185
        ///  572  189  424
        ///  842  206  272
        ///   55  656   94
        ///  612  375   90
        ///  663  550  179
        ///  183  487  470
        ///  551  664  431
        ///  714  728  853
        ///  548  456  329
        ///  531  783  592
        ///   49  749  478
        ///  529  866  959
        ///   94  883   73
        ///  438   33  953
        ///  818  113  644
        ///  839  111  817
        ///   41   54  276
        ///   82  464  354
        ///  891  567  488
        ///  909  559  165
        ///  752   53   36
        ///  797  146  382
        ///  700   94  368
        ///  121  944  167
        ///  125  262  102
        ///  152  720  123
        ///  410  205  520
        ///  810  760  469
        ///  529  733  243
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D03 {
            get {
                return ResourceManager.GetString("input_D03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aczupnetwp-dnlgpyrpc-sfye-dstaatyr-561[patyc]
        ///jsehsyafy-vqw-ljsafafy-866[nymla]
        ///tyepcyletzylw-ncjzrpytn-prr-opawzjxpye-743[cnrdl]
        ///foadouwbu-qvcqczohs-obozmgwg-662[lamjh]
        ///ckgvutofkj-pkrrehkgt-zkinturume-436[krtue]
        ///pelbtravp-pnaql-ernpdhvfvgvba-481[szram]
        ///yflexwxoalrp-ciltbo-tlohpelm-887[bmwep]
        ///ipvohghykvbz-ihzrla-jbzavtly-zlycpjl-253[lzhvy]
        ///cybyjqho-whqtu-rqiauj-fkhsxqiydw-322[syzwi]
        ///tipfxvezt-sleep-tljkfdvi-jvimztv-425[tveif]
        ///ktiaaqnqml-xtiabqk-oziaa-xczkpiaqvo-616[aiqko]
        ///ckgvutofkj-xghhoz-gtgrey [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D04 {
            get {
                return ResourceManager.GetString("input_D04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vlmbsivg
        ///wjskjzff
        ///hmcodblh
        ///nvohhghm
        ///xainmzpz
        ///frkckyrg
        ///zqdmvmee
        ///sbsqzlju
        ///eqdnsvqi
        ///xdmyqmxk
        ///gchzzkci
        ///unjukwld
        ///fmnpwrnf
        ///huvyqxkt
        ///uxekmktg
        ///pdzxhbfa
        ///khlkjqhk
        ///ravznzpy
        ///btpqmfzt
        ///tcnpghzn
        ///yuplhxzr
        ///ablaihve
        ///gjdehjcu
        ///dvmkpskx
        ///lukbiacr
        ///ttrzcksg
        ///ecfehhzq
        ///octwtlsc
        ///colisfrx
        ///svtipfzv
        ///kaffxell
        ///rsmdpuic
        ///viaidaip
        ///drbezwvb
        ///tyhnjseu
        ///weuopaqc
        ///igmqdwiz
        ///gerzveig
        ///bnqltmlo
        ///jgwcxybe
        ///iaabqazu
        ///bgflkfyt
        ///boznsgas
        ///agiyktkz
        ///ivvnbvuv
        ///tospvglb
        ///vxfhcvkz
        ///kshbpxws
        ///uejxthhb
        ///vyffdirv
        ///ibfywjob
        ///cp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D06 {
            get {
                return ResourceManager.GetString("input_D06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rhamaeovmbheijj[hkwbkqzlcscwjkyjulk]ajsxfuemamuqcjccbc
        ///gdlrknrmexvaypu[crqappbbcaplkkzb]vhvkjyadjsryysvj[nbvypeadikilcwg]jwxlimrgakadpxu[dgoanojvdvwfabtt]yqsalmulblolkgsheo
        ///dqpthtgufgzjojuvzvm[eejdhpcqyiydwod]iingwezvcbtowwzc[uzlxaqenhgsebqskn]wcucfmnlarrvdceuxqc[dkwcsxeitcobaylhbvc]klxammurpqgmpsxsr
        ///gmmfbtpprishiujnpdi[wedykxqyntvrkfdzom]uidgvubnregvorgnhm
        ///txxplravpgztjqcw[txgmmtlhmqpmmwp]bmhfgpmafxqwtrpr[inntmjmgqothdzfqgxq]cvtwvembpvdmcvk
        ///gkxjhpayoyrrpcr[mwyoahlkqyhtznyzrm]mvmurvsrgjunjjepn[mkoumuoh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D07 {
            get {
                return ResourceManager.GetString("input_D07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rect 1x1
        ///rotate row y=0 by 7
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 7
        ///rect 6x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 2
        ///rect 1x2
        ///rotate row y=1 by 10
        ///rotate row y=0 by 3
        ///rotate column x=0 by 1
        ///rect 2x1
        ///rotate column x=20 by 1
        ///rotate column x=15 by 1
        ///rot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input_D08 {
            get {
                return ResourceManager.GetString("input_D08", resourceCulture);
            }
        }
    }
}
